services:
    # php:
    #   container_name: php
    #   volumes:
    #     - ./php/php7.4.ini:/usr/local/etc/php/php.ini
    #     - ~/work/www:/var/www/html
    #     - /tmp:/tmp
    #   expose:
    #     - "9000"
    #   build:
    #     context: ./php
    #   ports:
    #     - 701:701
    #     - 702:702
    #     - 703:703
    #     - 704:704

    nginx:
      build:
        context: ./nginx
      container_name: nginx
      ports:
        - 80:80
        - 8080:8080
        - 443:443
      volumes:
        - ~/work/www:/usr/share/nginx/html
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        # - ./nginx/conf.d:/etc/nginx/conf.d
        - ./log/nginx:/var/log/nginx
    
    redis:
      build:
        context: ./redis
      container_name: redis
      volumes:
        - ./data/redis:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./log:/logs
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - 6379:6379


    rabbitmq:
      build:
        context: ./rabbitmq
      container_name: rabbitmq
      ports:
        - 15672:15672
        - 5672:5672
      volumes:
        - ./data/rabbitmq:/var/lib/rabbitmq
        - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        - ./rabbitmq/conf.d:/etc/rabbitmq/conf.d
        - ./log/rabbitmq:/var/log/rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=root
        - RABBITMQ_DEFAULT_PASS=root
    
    # mysql:
    #   platform: linux/amd64
    #   build:
    #     context: ./mysql
    #   container_name: mysql
    #   volumes:
    #     - ./log/mysql:/var/log/mysql
    #     - ./data/mysql:/var/lib/mysql
    #     - ./mysql/my.cnf:/etc/my.cnf
    #     # 数据库还原目录 可将需要还原的sql文件放在这里
    #     # - ./data/mysql/source:/docker-entrypoint-initdb.d
    #   environment:
    #     - "MYSQL_ROOT_PASSWORD=root"
    #     - "MYSQL_DATABASE="
    #     - "TZ=Asia/Shanghai"
    #   command: --default-authentication-plugin=mysql_native_password 
    #   ports:
    #     - 3306:3306