version: '3'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./php/php7.4.ini:/usr/local/etc/php/php.ini
      - /data/:/data/
    environment:
      - TZ=Asia/Shanghai
    restart: always
    stdin_open: true
    tty: true
    container_name: php
    ports:
      - 9000:9000
    # networks:
    #  dev:
    #    ipv4_address: 172.16.238.22

  mysql:
    restart: always
    image: mysql
    build: ./mysql
    container_name: mysql
    privileged: true
    volumes:
      - /data/db/mysql:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - /data/db/mysql-source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DATABASE: mydb
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  nginx:
    hostname: nginx
    image: nginx
    build:
      ./nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - /data/log/:/data/log:rw
      - /data/www/:/usr/local/nginx/html/
    restart: always
    container_name: nginx
    depends_on:
      - php
    environment:
      - TZ=Asia/Shanghai
    # networks:
    #  default:
    #    ipv4_address: 172.88.88.2

  redis:
    hostname: redis
    image: redis
    build:
      ./redis
    # volumes:
    #   - /data/db/redis/:/data/db/redis/:rw
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:rw
      - /data/db/redis/:/data/db/redis/:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes
    restart: always
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    # networks:
    #  default:
    #    ipv4_address: 172.88.88.3


# networks:
#   dev:
#     ipam:
#       driver: default
#       config:
#         - subnet: "172.16.238.0/24"
#           # gateway: 172.16.238.1
