version: '3'

# networks:
#   dev:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16

# networks:
#       dev:
#         ipv4_address: 172.28.0.12


services:
  php_dev:
    hostname: php_dev
    build:
      context: ./php
    volumes:
      - ./php/php7.4.ini:/usr/local/etc/php/php.ini
      - /data/:/data/
    environment:
      - TZ=Asia/Shanghai
    restart: always
    stdin_open: true
    tty: true
    container_name: php_dev
    image: php_dev
    ports:
      - 9000:9000

  mysql_dev:
    hostname: mysql_dev
    restart: always
    image: mysql_dev
    build: ./mysql
    container_name: mysql_dev
    privileged: true
    volumes:
      - /data/db/mysql:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - /data/db/mysql-source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DATABASE: mydb
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  nginx_dev:
    hostname: nginx_dev
    image: nginx_dev
    build:
      ./nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - /data/log/:/data/log:rw
      - /data/www/:/usr/local/nginx/html/
    restart: always
    container_name: nginx_dev
    depends_on:
      - php_dev
    environment:
      - TZ=Asia/Shanghai

  redis_dev:
    hostname: redis_dev
    image: redis_dev
    build:
      ./redis
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:rw
      - /data/db/redis/:/data/db/redis/:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes
    restart: always
    container_name: redis_dev
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379

  rabbitmq_dev:
    hostname: rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_VHOST: "rabbitmq"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    image: daocloud.io/library/rabbitmq:3.6.9-management
    container_name: rabbitmq_dev
    restart: always
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq:rw
      - /data/log/rabbitmq:/var/log/rabbitmq/log:rw
    ports:
      - "15672:15672" # 管理界面ui端口
      - "4369:4369" #erlang发现口
      - "5672:5672" # client端通信口
      - "25672:25672" # server间内部通信口

